name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Build binary and JS artifact
        run: nix-shell --run "sbt graalvm-native-image:packageBin;fullOptJS"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./.jvm/target/graalvm-native-image/rainbow-parens,.js/rainbow-parens.js"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
