name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Build binary
        run: nix-shell --run "sbt graalvm-native-image:packageBin"
      - name: Copy result to system-suffixed name
        run: |
          cp ./target/graalvm-native-image/rainbow-parens ./rainbow-parens-${RUNNER_ARCH}-${RUNNER_OS}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./rainbow-parens-$env:RUNNER_ARCH-$env:RUNNER_OS"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
